### ISSUE TITLE
Integrate with cloudwatch

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/cloud-ops#112]
- [x] Add an AWS service + boto3 integration for cloudwatch.
- [x] Should be able to collect system metrics (CPU, RAM, Disk, Network data etc) given an ec2 instance's ARN.
- [x] Research what else can be collected.

**Comment by Kelton8Z** [comment]
Apart from CPU, RAM, Disk, Network data, other EC2 instance metrics available are 
- EBS(Elastic Block Store) metrics for Nitro-based(as opposed to bare metal) instances 
- Status check metrics (1-minute frequency at no charge)
- Traffic mirroring metrics
- usage metrics(vCPU use, resource count, and resource type)

as listed in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html
